runtime: python37
entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /img
    static_dir: static/img
  - url: /scripts
    static_dir: static/scripts
  - url: /fonts
    static_dir: static/fonts
  - url: /style
    static_dir: static/style
  - url: /.*
    secure: always
    script: auto



