runtime: python36
version: 1
api_version: 1
threadsafe: true


handlers:
  -url: /img
  static_dir: static/img
  -url: /scripts
  static_dir: static/scripts
  -url: /fonts
  static_dir: static/fonts
  -url: /style
  static_dir: static/style
  -url: /.*
  secure: always
  script: app.py

libraries:
  -name: ssl
  version: latest

